SELECT TOP (1000) [idTarea]
      ,[idLote]
      ,[idCliente]
      ,[NombreCliente]
      ,[idEstadoTarea]
      ,[FechaHoraProxEjecucion]
      ,[Prioridad]
      ,[PrioridadRellamada]
      ,[Puntaje]
      ,[CantidadIntentos]
      ,[UltimoCodigoTerminacion]
      ,[UltimoResultadoGestion]
      ,[UltimoIdCRM]
      ,[UltimoIdAgente]
      ,[FechaHoraUltimoContacto]
      ,[UltimoNumeroDiscado]
      ,[idAgente]
      ,[AlarmaSet]
      ,[idOperacion]
      ,[FechaUltimaGestion]
      ,[idAgenteUltimaGestion]
      ,[idEstadoBPM]
      ,[idCaso]
  FROM [MitACD].[dbo].[Tareas_Tareas]